export const ACCENT = '#8b5cf6';

export const WAITLIST_ENDPOINT = import.meta.env.VITE_WAITLIST_ENDPOINT || '';

export const PILLAR_ICONS = {
  identity: '<path d="M8 13a3 3 0 1 0 0-6 3 3 0 0 0 0 6Z"/><path d="M2 20c0-2.8 2.5-5 6-5s6 2.2 6 5"/><path d="M15 8a2.5 2.5 0 1 1 0-5"/><path d="M22 19c0-2.2-1.8-4-4.5-4"/>',
  domain: '<circle cx="12" cy="12" r="9"/><path d="M3 12h18"/><path d="M12 3a13 13 0 0 1 0 18"/><path d="M12 3a13 13 0 0 0 0 18"/>',
  website: '<rect x="3" y="4" width="18" height="15" rx="2"/><path d="M3 9h18"/><circle cx="6.5" cy="6.5" r="0.6" fill="currentColor" stroke="none"/>',
  email: '<rect x="3" y="5" width="18" height="14" rx="2"/><path d="m3 7 9 6 9-6"/>',
  visibility: '<path d="M4 19h16"/><path d="M6 15l4-5 4 3 5-7"/><path d="M15 6h4v4"/>',
  trust: '<path d="M12 3l7 3v6c0 4.5-3 7.5-7 9-4-1.5-7-4.5-7-9V6z"/><path d="m9.5 12 2 2 3.5-4"/>',
};

export const PILLARS = [
  { key: 'identity' },
  { key: 'domain' },
  { key: 'website' },
  { key: 'email' },
  { key: 'visibility' },
  { key: 'trust' },
];

export const SERVICE_ICONS = {
  email: '<rect x="3" y="5" width="18" height="14" rx="2"/><path d="m3 7 9 6 9-6"/>',
  domain: '<circle cx="12" cy="12" r="9"/><path d="M3 12h18"/><path d="M12 3a13 13 0 0 1 0 18"/><path d="M12 3a13 13 0 0 0 0 18"/>',
  website: '<rect x="3" y="4" width="18" height="15" rx="2"/><path d="M3 9h18"/>',
  hosting: '<rect x="3" y="4" width="18" height="6" rx="1.5"/><rect x="3" y="14" width="18" height="6" rx="1.5"/><circle cx="7" cy="7" r="0.6" fill="currentColor" stroke="none"/><circle cx="7" cy="17" r="0.6" fill="currentColor" stroke="none"/>',
  other: '<circle cx="12" cy="12" r="9"/><circle cx="8" cy="12" r="0.8" fill="currentColor" stroke="none"/><circle cx="12" cy="12" r="0.8" fill="currentColor" stroke="none"/><circle cx="16" cy="12" r="0.8" fill="currentColor" stroke="none"/>',
};

export const SERVICES = [
  { key: 'email' },
  { key: 'domain' },
  { key: 'website' },
  { key: 'hosting' },
  { key: 'other' },
];

export const COUNTRIES = [
  { code: 'SA', name: 'Saudi Arabia', dial: '966', flag: '🇸🇦' },
  { code: 'AE', name: 'United Arab Emirates', dial: '971', flag: '🇦🇪' },
  { code: 'KW', name: 'Kuwait', dial: '965', flag: '🇰🇼' },
  { code: 'QA', name: 'Qatar', dial: '974', flag: '🇶🇦' },
  { code: 'BH', name: 'Bahrain', dial: '973', flag: '🇧🇭' },
  { code: 'OM', name: 'Oman', dial: '968', flag: '🇴🇲' },
  { code: 'EG', name: 'Egypt', dial: '20', flag: '🇪🇬' },
  { code: 'JO', name: 'Jordan', dial: '962', flag: '🇯🇴' },
  { code: 'LB', name: 'Lebanon', dial: '961', flag: '🇱🇧' },
  { code: 'IQ', name: 'Iraq', dial: '964', flag: '🇮🇶' },
  { code: 'YE', name: 'Yemen', dial: '967', flag: '🇾🇪' },
  { code: 'SY', name: 'Syria', dial: '963', flag: '🇸🇾' },
  { code: 'PS', name: 'Palestine', dial: '970', flag: '🇵🇸' },
  { code: 'MA', name: 'Morocco', dial: '212', flag: '🇲🇦' },
  { code: 'DZ', name: 'Algeria', dial: '213', flag: '🇩🇿' },
  { code: 'TN', name: 'Tunisia', dial: '216', flag: '🇹🇳' },
  { code: 'LY', name: 'Libya', dial: '218', flag: '🇱🇾' },
  { code: 'SD', name: 'Sudan', dial: '249', flag: '🇸🇩' },
  { code: 'US', name: 'United States', dial: '1', flag: '🇺🇸' },
  { code: 'GB', name: 'United Kingdom', dial: '44', flag: '🇬🇧' },
  { code: 'CA', name: 'Canada', dial: '1', flag: '🇨🇦' },
  { code: 'FR', name: 'France', dial: '33', flag: '🇫🇷' },
  { code: 'DE', name: 'Germany', dial: '49', flag: '🇩🇪' },
  { code: 'ES', name: 'Spain', dial: '34', flag: '🇪🇸' },
  { code: 'IT', name: 'Italy', dial: '39', flag: '🇮🇹' },
  { code: 'TR', name: 'Turkey', dial: '90', flag: '🇹🇷' },
  { code: 'IN', name: 'India', dial: '91', flag: '🇮🇳' },
  { code: 'PK', name: 'Pakistan', dial: '92', flag: '🇵🇰' },
  { code: 'BD', name: 'Bangladesh', dial: '880', flag: '🇧🇩' },
  { code: 'PH', name: 'Philippines', dial: '63', flag: '🇵🇭' },
  { code: 'ID', name: 'Indonesia', dial: '62', flag: '🇮🇩' },
  { code: 'MY', name: 'Malaysia', dial: '60', flag: '🇲🇾' },
  { code: 'CN', name: 'China', dial: '86', flag: '🇨🇳' },
  { code: 'JP', name: 'Japan', dial: '81', flag: '🇯🇵' },
  { code: 'KR', name: 'South Korea', dial: '82', flag: '🇰🇷' },
  { code: 'AU', name: 'Australia', dial: '61', flag: '🇦🇺' },
  { code: 'ZA', name: 'South Africa', dial: '27', flag: '🇿🇦' },
  { code: 'NG', name: 'Nigeria', dial: '234', flag: '🇳🇬' },
  { code: 'BR', name: 'Brazil', dial: '55', flag: '🇧🇷' },
];

export const T = {
  en: {
    nav: { why: 'Why Wojood', offer: 'What We Offer', early: 'Early Access', coming: 'Coming Soon' },
    errors: {
      name: 'Please enter your name.',
      emailRequired: 'Please enter your email address.',
      email: 'Please enter a valid email address.',
      phoneRequired: 'Please enter your mobile number.',
      phone: 'Please enter a valid mobile number.',
      businessType: 'Please select your business type.',
      services: 'Please select at least one service.',
      generic: 'Something went wrong. Please try again.',
    },
    countrySearchPlaceholder: 'Search country or code',
    businessSearchPlaceholder: 'Search business type',
    businessNoResults: 'No business types found',
    hero: {
      eyebrow: '',
      headline: 'Your partner for a digital presence.',
      desc1: 'Your online presence is more than a domain.',
      desc2: "It's the first thing people see and the foundation of trust.",
      cta1: 'Get Early Access ',
      cta2: 'Explore WOJOD ↓',
    },
    why: {
      heading1: 'Why do you need ',
      heading2: 'Wojod',
      heading3: '?',
      closingWojod: '',
      closingRest: '',
      p1: 'Scattered tools. Multiple providers. Different ways of doing things.',
      p2: 'They consume your time and effort, pulling your focus away from what matters.',
      closing1: "You're building your business. ",
      closingBreak: true,
      closing2: "You shouldn't have to ",
      closing3: 'piece it together',
      closing4: '.',
    },
    offer: {
      heading1: 'Wojood. Your digital presence, in ',
      heading2: 'one place.',
      desc: "More than a domain or a website. It's everything you need to show up, stand out, and grow — all in one place.",
      pillars: {
        identity: 'Digital Identity',
        domain: 'Domain',
        website: 'Website',
        email: 'Professional Email',
        visibility: 'Online Visibility',
        trust: 'Trust & Security',
      },
    },
    early: {
      headline1: 'Be part of ',
      headline2: 'WOJOD.',
      desc: "We're building a simpler way to create your digital presence. Join from the start, and be among the first to discover WOJOD and help shape it.",
      priority: 'Early access',
      updates: 'Priority experience',
      voice: 'Your voice makes a difference',
      formTitle: 'Join the waitlist',
      formSubtitle: 'Be among the first to experience Wojood.',
      fullName: 'Full name',
      email: 'Email address',
      phone: 'Mobile number',
      businessTypeLabel: 'Your business type',
      businessTypePlaceholder: 'Select your business type',
      servicesLabel: 'What services are you interested in?',
      servicesSub: 'Select all that apply',
      privacy: 'We respect your privacy. No spam, ever.',
      ctaIdle: 'Join the waitlist',
      ctaSubmitting: 'Joining...',
      ctaSuccess: "✓ You're in",
      success: "You're on the list.",
      successSub: "We'll keep you updated when WOJOD is ready.",
      duplicate: "You're already on the list.",
      genericError: 'Something went wrong. Please try again.',
      services: { email: 'Email', domain: 'Domain', website: 'Website', hosting: 'Hosting', other: 'Other' },
      modal: {
        successTitle: "You're on the list",
        successBody: "Your place has been reserved for early access to WOJOD. We'll be in touch when there's something worth sharing.",
        successBtn: 'Got it ✓',
        duplicateTitle: "You're already on the list",
        duplicateBody: 'Your interest has already been registered, and your place is reserved for early access to WOJOD.',
        duplicateBtn: 'Got it ✓',
        errorTitle: 'Something went wrong',
        errorBody: "We couldn't complete your registration this time. Please try again.",
        errorBtn: 'Try again',
      },
    },
    footer: { copyright: '© 2026 WOJOD Inc.', privacy: 'Privacy Policy', terms: 'Terms of Service', contact: 'Contact' },
  },
  ar: {
    nav: { why: 'لماذا وجود', offer: 'ماذا نقدم', early: 'الوصول المبكر', coming: 'قريبًا' },
    errors: {
      name: 'يرجى إدخال اسمك.',
      emailRequired: 'يرجى إدخال بريدك الإلكتروني.',
      email: 'يرجى إدخال بريد إلكتروني صحيح.',
      phoneRequired: 'يرجى إدخال رقم جوالك.',
      phone: 'يرجى إدخال رقم جوال صحيح.',
      businessType: 'يرجى اختيار نوع نشاطك.',
      services: 'يرجى اختيار خدمة واحدة على الأقل.',
      generic: 'حدث خطأ ما. يرجى المحاولة مرة أخرى.',
    },
    countrySearchPlaceholder: 'ابحث عن دولة أو رمز',
    businessSearchPlaceholder: 'ابحث عن نوع نشاطك',
    businessNoResults: 'لم نجد نوع نشاط مطابق',
    hero: {
      eyebrow: 'وجود',
      headline: 'شريكك لبناء حضور رقمي موثوق ينمو معك.',
      desc1: 'وجودك على الإنترنت ليس مجرد عنوان.',
      desc2: 'إنه أول ما يُرى عنك، وأول ما يُبنى عليه الانطباع والثقة.',
      cta1: 'سجّل اهتمامك مبكرًا',
      cta2: 'استكشف WOJOD ↓',
    },
    why: {
      heading1: 'حضورك الرقمي يستحق أن يكون ',
      heading2: 'أبسط',
      heading3: '. ',
      p1: 'نطاق، موقع، بريد، وخدمات متعددة. أساسيات مهمة، لكن تشتتها بين منصات ومزودين مختلفين يجعل بناء حضور متكامل أكثر تعقيدًا مما ينبغي.',
      p2: '',
      closing1: '',
      closingWojod: 'WOJOD',
      closingRest: ' يجمع لك الأساس في مكان واحد، لتبني حضورك الرقمي بثقة، ويكبر معك خطوة بخطوة.  ',
      closingBreak: false,
      closing2: '',
      closing3: '',
      closing4: '',
    },
    offer: {
      heading1: 'حضورك الرقمي، ',
      heading2: 'في مكان واحد.',
      desc: 'أكثر من نطاق أو موقع إلكتروني. كل ما تحتاجه لتظهر، وتتميز، وتنمو — في مكان واحد.',
      pillars: {
        identity: 'الهوية الرقمية',
        domain: 'النطاق',
        website: 'الموقع الإلكتروني',
        email: 'البريد الاحترافي',
        visibility: 'الظهور الرقمي',
        trust: 'الثقة والأمان',
      },
    },
    early: {
      headline1: 'كن جزءًا من ',
      headline2: 'WOJOD.',
      desc: 'نسعى لبناء طريقة أبسط لبناء حضورك الرقمي. انضم من البداية، وكن من أوائل من يكتشفون WOJOD ويشاركون في تشكيله.',
      priority: 'وصول مبكر',
      updates: 'أولوية التجربة',
      voice: 'صوتك يصنع الفرق',
      formTitle: 'انضم إلى قائمة الانتظار',
      formSubtitle: 'كن من أوائل من يختبرون وجود.',
      fullName: 'الاسم الكامل',
      email: 'البريد الإلكتروني',
      phone: 'رقم الجوال',
      businessTypeLabel: 'نوع نشاطك',
      businessTypePlaceholder: 'اختر نوع نشاطك',
      servicesLabel: 'ما الخدمات التي تهمك؟',
      servicesSub: 'اختر كل ما ينطبق عليك',
      privacy: 'نحترم خصوصيتك. لا رسائل مزعجة.',
      ctaIdle: 'انضم إلى قائمة الانتظار',
      ctaSubmitting: 'جارٍ الانضمام...',
      ctaSuccess: '✓ تم الانضمام',
      success: 'تم تسجيل اهتمامك.',
      successSub: 'سنوافيك بكل جديد عند اقتراب إطلاق WOJOD.',
      duplicate: 'أنت مسجل بالفعل.',
      genericError: 'حدث خطأ. حاول مرة أخرى.',
      services: { email: 'البريد الإلكتروني', domain: 'النطاق', website: 'الموقع الإلكتروني', hosting: 'الاستضافة', other: 'أخرى' },
      modal: {
        successTitle: 'تم تسجيل اهتمامك',
        successBody: 'تم حجز مكانك ضمن الوصول المبكر إلى WOJOD. سنكون على تواصل معك قريبًا بكل جديد.',
        successBtn: 'رائع، شكرًا لك',
        duplicateTitle: 'أنت مسجل بالفعل',
        duplicateBody: 'تم تسجيل اهتمامك مسبقًا، ومكانك محفوظ ضمن الوصول المبكر إلى WOJOD.',
        duplicateBtn: 'ممتاز ✓',
        errorTitle: 'لم نتمكن من تسجيل طلبك',
        errorBody: 'حدث خطأ بسيط أثناء التسجيل. حاول مرة أخرى، وسنكون بانتظارك.',
        errorBtn: 'حاول مرة أخرى',
      },
    },
    footer: { copyright: '© 2026 وجود', privacy: 'سياسة الخصوصية', terms: 'شروط الخدمة', contact: 'تواصل معنا' },
  },
};

export const BUSINESS_TYPES_EN = {
  health: 'Health & Wellness',
  tech: 'Technology & Software',
  retail: 'Retail & E-commerce',
  hospitality: 'Hospitality & Food',
  finance: 'Finance & Banking',
  law: 'Law & Legal Services',
  education: 'Education & Training',
  'real-estate': 'Real Estate & Construction',
  beauty: 'Beauty & Personal Care',
  fitness: 'Fitness & Sports',
  'professional-services': 'Professional Services & Consulting',
  creative: 'Creative, Media & Marketing',
  manufacturing: 'Manufacturing & Industrial',
  logistics: 'Logistics & Transportation',
  automotive: 'Automotive',
  agriculture: 'Agriculture & Food Production',
  energy: 'Energy & Utilities',
  travel: 'Travel & Tourism',
  nonprofit: 'Nonprofit & Government',
  events: 'Events & Entertainment',
  other: 'Other',
};

export const BUSINESS_TYPES_AR = {
  health: 'الصحة والعافية',
  tech: 'التقنية والبرمجيات',
  retail: 'التجزئة والتجارة الإلكترونية',
  hospitality: 'الضيافة والأغذية',
  finance: 'المالية والمصرفية',
  law: 'القانون والخدمات القانونية',
  education: 'التعليم والتدريب',
  'real-estate': 'العقارات والإنشاءات',
  beauty: 'التجميل والعناية الشخصية',
  fitness: 'اللياقة والرياضة',
  'professional-services': 'الخدمات المهنية والاستشارات',
  creative: 'الإبداع والإعلام والتسويق',
  manufacturing: 'التصنيع والصناعة',
  logistics: 'الخدمات اللوجستية والنقل',
  automotive: 'السيارات',
  agriculture: 'الزراعة والإنتاج الغذائي',
  energy: 'الطاقة والمرافق',
  travel: 'السفر والسياحة',
  nonprofit: 'القطاع غير الربحي والحكومي',
  events: 'الفعاليات والترفيه',
  other: 'أخرى',
};
